# Generated by Django 2.2.2 on 2019-06-22 14:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190622_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
